const constants = {
    AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
    AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
    AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
    AUTH_LOGOUT: 'AUTH_LOGOUT',

    AUTH_REGISTER_REQUEST: 'AUTH_REGISTER_REQUEST',
    AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
    AUTH_REGISTER_FAIL: 'AUTH_REGISTER_FAIL',

    AUTH_PROFILE_REQUEST: 'AUTH_PROFILE_REQUEST',
    AUTH_PROFILE_SUCCESS: 'AUTH_PROFILE_SUCCESS',
    AUTH_PROFILE_FAIL: 'AUTH_PROFILE_FAIL',
    AUTH_PROFILE_RESET: 'AUTH_PROFILE_RESET',

    AUTH_UPDATE_PROFILE_REQUEST: 'AUTH_UPDATE_PROFILE_REQUEST',
    AUTH_UPDATE_PROFILE_SUCCESS: 'AUTH_UPDATE_PROFILE_SUCCESS',
    AUTH_UPDATE_PROFILE_FAIL: 'AUTH_UPDATE_PROFILE_FAIL',
    AUTH_UPDATE_PROFILE_RESET: 'AUTH_UPDATE_PROFILE_RESET',
};
export default constants;
