const constants = {
    CART_ADD_ITEM: 'CART_ADD_ITEM',
    CART_UPDATE_ITEM: 'CART_UPDATE_ITEM',
    CART_UPDATE_ITEM: 'CART_UPDATE_ITEM',
    CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
    CART_SAVE_PAYMENT_METHOD: 'CART_SAVE_PAYMENT_METHOD',
    CART_SAVE_SHIPPING_INFO: 'CART_SAVE_SHIPPING_INFO',
    CART_RESET: 'CART_RESET',
};
export default constants;
