const constants = {
    GET_REVENUE_REQUEST: 'GET_REVENUE_REQUEST',
    GET_REVENUE_SUCCESS: 'GET_REVENUE_SUCCESS',
    GET_REVENUE_FAIL: 'GET_REVENUE_FAIL',
    GET_REVENUE_RESET: 'GET_REVENUE_RESET',

    GET_TOP_PRODUCT_REQUEST: 'GET_TOP_PRODUCT_REQUEST',
    GET_TOP_PRODUCT_SUCCESS: 'GET_TOP_PRODUCT_SUCCESS',
    GET_TOP_PRODUCT_FAIL: 'GET_TOP_PRODUCT_FAIL',
    GET_TOP_PRODUCT_RESET: 'GET_TOP_PRODUCT_RESET',
};
export default constants;