const constants = {
    IMPORT_CREATE_REQUEST: 'IMPORT_CREATE_REQUEST',
    IMPORT_CREATE_SUCCESS: 'IMPORT_CREATE_SUCCESS',
    IMPORT_CREATE_FAIL: 'IMPORT_CREATE_FAIL',
    IMPORT_CREATE_RESET: 'IMPORT_CREATE_RESET',

    IMPORT_ALL_REQUEST: 'IMPORT_ALL_REQUEST',
    IMPORT_ALL_SUCCESS: 'IMPORT_ALL_SUCCESS',
    IMPORT_ALL_FAIL: 'IMPORT_ALL_FAIL',
    IMPORT_ALL_RESET: 'IMPORT_LISTS_RESET',

    IMPORT_DETAIL_REQUEST: 'IMPORT_DETAIL_REQUEST',
    IMPORT_DETAIL_SUCCESS: 'IMPORT_DETAIL_SUCCESS',
    IMPORT_DETAIL_FAIL: 'IMPORT_DETAIL_FAIL',
};
export default constants;
