const constants = {
    ORDER_CREATE_REQUEST: 'ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL: 'ORDER_CREATE_FAIL',
    ORDER_CREATE_RESET: 'ORDER_CREATE_RESET',

    ORDER_DETAILS_REQUEST: 'ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SUCCESS: 'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAIL: 'ORDER_DETAILS_FAIL',

    ORDER_PAY_REQUEST: 'ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS: 'ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL: 'ORDER_PAY_FAIL',
    ORDER_PAY_RESET: 'ORDER_PAY_RESET',

    ORDER_MY_LIST_REQUEST: 'ORDER_MY_LIST_REQUEST',
    ORDER_MY_LIST_SUCCESS: 'ORDER_MY_LIST_SUCCESS',
    ORDER_MY_LIST_FAIL: 'ORDER_MY_LIST_FAIL',
    ORDER_MY_LIST_RESET: 'ORDER_MY_LIST_RESET',

    ORDER_LISTS_REQUEST: 'ORDER_LISTS_REQUEST',
    ORDER_LISTS_SUCCESS: 'ORDER_LISTS_SUCCESS',
    ORDER_LISTS_FAIL: 'ORDER_LISTS_FAIL',
    ORDER_LISTS_RESET: 'ORDER_LISTS_RESET',

    ORDER_UPDATE_STATUS_REQUEST: 'ORDER_UPDATE_STATUS_REQUEST',
    ORDER_UPDATE_STATUS_SUCCESS: 'ORDER_UPDATE_STATUS_SUCCESS',
    ORDER_UPDATE_STATUS_FAIL: 'ORDER_UPDATE_STATUS_FAIL',
    ORDER_UPDATE_STATUS_RESET: 'ORDER_UPDATE_STATUS_RESET',

    ORDER_CANCEL_REQUEST: 'ORDER_CANCEL_REQUEST',
    ORDER_CANCEL_SUCCESS: 'ORDER_CANCEL_SUCCESS',
    ORDER_CANCEL_FAIL: 'ORDER_CANCEL_FAIL',
    ORDER_CANCEL_RESET: 'ORDER_CANCEL_RESET',
};
export default constants;
