const constants = {
    PRODUCT_FILTER_REQUEST: 'PRODUCT_FILTER_REQUEST',
    PRODUCT_FILTER_SUCCESS: 'PRODUCT_FILTER_SUCCESS',
    PRODUCT_FILTER_FAIL: 'PRODUCT_FILTER_FAIL',

    PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: 'PRODUCT_LIST_FAIL',

    PRODUCT_DETAIL_REQUEST: 'PRODUCT_DETAIL_REQUEST',
    PRODUCT_DETAIL_SUCCESS: 'PRODUCT_DETAIL_SUCCESS',
    PRODUCT_DETAIL_FAIL: 'PRODUCT_DETAIL_FAIL',

    PRODUCT_ALL_REQUEST: 'PRODUCT_ALL_REQUEST',
    PRODUCT_ALL_SUCCESS: 'PRODUCT_ALL_SUCCESS',
    PRODUCT_ALL_FAIL: 'PRODUCT_ALL_FAIL',

    PRODUCT_CREATE_REVIEW_REQUEST: 'PRODUCT_CREATE_REVIEW_REQUEST',
    PRODUCT_CREATE_REVIEW_SUCCESS: 'PRODUCT_CREATE_REVIEW_SUCCESS',
    PRODUCT_CREATE_REVIEW_FAIL: 'PRODUCT_CREATE_REVIEW_FAIL',
    PRODUCT_CREATE_REVIEW_RESET: 'PRODUCT_CREATE_REVIEW_RESET',

    PRODUCT_DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAIL: 'PRODUCT_DELETE_FAIL',
    PRODUCT_DELETE_RESET: 'PRODUCT_DELETE_RESET',

    PRODUCT_UPDATE_REQUEST: 'PRODUCT_UPDATE_REQUEST',
    PRODUCT_UPDATE_SUCCESS: 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_FAIL: 'PRODUCT_UPDATE_FAIL',
    PRODUCT_UPDATE_RESET: 'PRODUCT_UPDATE_RESET',

    PRODUCT_CREATE_REQUEST: 'PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_FAIL: 'PRODUCT_CREATE_FAIL',
    PRODUCT_CREATE_RESET: 'PRODUCT_CREATE_RESET',
};

export default constants;
