const constants = {
    RATING_ALL_REQUEST: 'RATING_ALL_REQUEST',
    RATING_ALL_SUCCESS: 'RATING_ALL_SUCCESS',
    RATING_ALL_FAIL: 'RATING_ALL_FAIL',

    RATING_CREATE_REQUEST: 'RATING_CREATE_REQUEST',
    RATING_CREATE_SUCCESS: 'RATING_CREATE_SUCCESS',
    RATING_CREATE_FAIL: 'RATING_CREATE_FAIL',
    RATING_CREATE_RESET: 'RATING_CREATE_RESET',
};

export default constants;
